version: "3.8"

services:
  postgres:
    image: postgres:17.5
    container_name: eduliv-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eduliv-network

volumes:
  postgres_data:
    driver: local

networks:
  eduliv-network:
    driver: bridge
